namespace DomainDef
{
    public enum TokenType
    {
        OpenParen,
        CloseParen,
        Comma,
        Name,
        EndOfFile,
        Integer,
        Entity,
        Ident,
        Decimal,
        Bool,
        String,
        Int,
        Unique,
        Form,
        Domain,
        Property,
        StartOfFile,
        Default,
        Value,
        None,
        Ref,
        Short,
        Byte,
        Long,
        Field,
        Page,
        Grid
    }
}